repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]  # Use LF line endings (or --fix=crlf for Windows)

  - repo: https://github.com/psf/black
    rev: 23.12.1  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3  # or specify your Python version
