[project]
name = "akshay-trading-5"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.2",
    "loguru>=0.7.3",
    "pyzmq>=26.4.0",
    "requests>=2.32.3",
    "websocket>=0.2.1",
]
