[project]
name = "akshay-trading-5"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "cryptography>=45.0.2",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "loguru>=0.7.3",
    "manim>=0.19.0",
    "pandas>=2.2.3",
    "pre-commit>=4.2.0",
    "pyside6>=6.9.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "pytest-mock>=3.14.0",
    "pyzmq>=26.4.0",
    "qasync>=0.27.1",
    "requests>=2.32.3",
    "scipy>=1.15.3",
    "websocket>=0.2.1",
    "websockets>=15.0.1",
    "yt-dlp>=2025.6.9",
]
